
server:
  port: 9393
spring:
  influx:
    url: http://127.0.0.1:8086
    userName: admin
    password: admin
    database: lyy_test
    retention_policy: default
    retention_policy_time: 30d
  rabbitmq:
    virtual-host: test
    username: lyy
    password: 970120
    port: 5672
    host: 127.0.0.1
    publisher-confirms: true
    exchange: lyy1
  application:
    name: lyy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/lyy?characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 50000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      #最小能够保持idel状态的对象数
      min-idle: 50
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
    database: 0
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
thread:
  CORE_POOL_SIZE: 20
  MAX_POOL_SIZE: 100
  QUEUE_CAPACITY: 30
lyy:
  myConfig:
  switchConfig:
  entryCode: A059
  exitCode: O008
  entryCodePer: A095
  exitCodePer: O010
json:
  class-type: fastjson
security:
  user:
    password: lyy
    name: lyy
  basic:
    enabled: true
# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY : true

# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN : true

# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL : /api/

# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL : /interface-ui/

# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT : mysql

prop:
  fileStorePath: D:\SW\